### ISSUE TITLE
MathQuill EditableField에 작성되는 수식 모양 문제

### ISSUE THREAD

**Issue by Woomin-Jeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#18]
### 👉 Problem 
- 현재 MathQuill EditableField에 작성되는 수식은 padding 값을 이용해서 상하좌우 정렬이 되고 있는데 이는 정상적인 방법이 아니라고 판단됩니다.

### 🏀 Solution
- 마땅히 떠오르는 방법이 없습니다.

### 👊 So We
- 같이 생각해보면 좋을 것 같습니다.

**Comment by ByeongjaeJeon** [comment]
전체 수식이 표현되는 mq-math-mode 말씀하시는 건가요
아니면 수식 하나하나 span이나 var들을 말씀하시는 건가요?

**Comment by seokju2ng** [comment]
좌우정렬 말씀하시는 거면 현재 `text-align`으로 되고 있는 것 같은데요?

**Comment by Woomin-Jeon** [comment]
자랑스러운 저희 팀원분들이 몰래 해결해 놓으셨네요 ㅎㅎ :+1:
