### ISSUE TITLE
사이드 바 외부 영역 클릭 시 닫히도록 하는 기능

### ISSUE THREAD

**Issue by Woomin-Jeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#28]
### 🤙 To Do 
- [x] 사이드 바 외부 영역을 클릭하면 사이드 바가 닫히도록 한다.

**Comment by ByeongjaeJeon** [comment]
좋은 생각인 거 같습니다
사이드 바 보다가 수식 화면 누르면 사이드 바가 들어가서 화면이나 버튼 가리지 않으면 좋겠는데
버튼 메뉴처럼 사이드 바도 외부 누르면 닫히게 하면 좋겠네요

**Comment by seokju2ng** [comment]
굿굿 좋은 아이디어입니닷
