### ISSUE TITLE
사이드바 최근 수식/북마크 탭에서 커스텀 추가 버튼 클릭시 커스텀명에 focus 기능

### ISSUE THREAD

**Issue by seokju2ng** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#29]
### 🤙 To Do 
- [x] 사이드바 최근 수식/북마크 탭에서 +(커스텀 생성) 버튼 클릭하면 커스텀 폼에서 name 필드에 focus 해주는 기능 구현

**Comment by enhakkore** [comment]
폼 생성 후 name 필드에 focus 해주면 좋을 것 같습니다 👍

**Comment by enhakkore** [comment]
name 필드에 autoFocus 속성을 주면 자동으로 focus가 되긴 합니다!!
