### ISSUE TITLE
커스텀 명령어 사용 여부 검증 로직 최적화

### ISSUE THREAD

**Issue by Woomin-Jeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#44]
### 🤙 To Do 
- [x] 현재는 커스텀 명령어를 onChange마다 검사를해서 변경해주고 있는데, 이렇게 되면 성능상 연산이 너무 빈번하게 발생하므로 keydown 이벤트 등을 이용해서 space 입력시에만 검사하도록 최적화한다.

**Comment by ByeongjaeJeon** [comment]
자동 완성 기능으로 인해 커스텀 명령어를 입력할 때 space 입력 시 자동 완성이 이루어지도록 할 예정이므로 이 기능에 대한 이슈는 닫겠습니다.!
