### ISSUE TITLE
Github action 에서 테스트 통과해야 배포되도록 변경하기

### ISSUE THREAD

**Issue by ByeongjaeJeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#49]
### 👉 Problem 
- 테스트가 통과되든 안되든 빌드하고 배포한다.

### 🏀 Solution
- 테스트가 통과되어야 빌드, 배포되게 한다.

### 👊 So We
- [x] 테스트 작성하기
- [x] 테스트 통과해야 빌드/배포 되도록 변경하기

**Comment by Woomin-Jeon** [comment]
구현 완료
