### ISSUE TITLE
nCloud Object Storage로 이전

### ISSUE THREAD

**Issue by Woomin-Jeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#50]
### 🤙 To Do 
- [ ] 현재 사용 중인 netlify의 초기 로딩이 오래걸리는 이슈가 있어서 nCloud Object Storage로 이전한다
- [ ] location.origin -> location.href로 변경

**Comment by seokju2ng** [comment]
루트로 리다이렉션 해줄 때 발생하는 이슈와 일일이 퍼블릭하게 변경해줘야하는 이슈는 해결 가능할까요?

**Comment by Woomin-Jeon** [comment]
안하기로 결정해서 이슈를 닫습니다.
