### ISSUE TITLE
MathQuill StaticField에 있는 루트가 깨지는 문제

### ISSUE THREAD

**Issue by Woomin-Jeon** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#71]
### 👉 Problem 
- StaticField 안에 있는 루트의 모양이 깨짐

### 🏀 Solution
- 딱히 떠오르지 않음

### 👊 So We
- 같이 해결해야 할 듯

**Comment by enhakkore** [comment]
![image](https://user-images.githubusercontent.com/46911854/101856709-30d96f00-3ba9-11eb-9f7e-7d81af08ef40.png)

그렇네요...ㅠㅠ
