### ISSUE TITLE
사이드바 아이템(최근수식, 북마크, 커스텀 명령어) 접근성 높이기

### ISSUE THREAD

**Issue by enhakkore** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#80]
### 🤙 To Do 
- [x] 삭제 버튼 찾기 쉽게 만들기
- [x] 커스텀 아이템의 height 수정하기
- [x] EmptyIcon과 커스터 명령어 폼이 겹치는 문제 해결하기
- [x] 아이템에 hover하면 나타나는 레이아웃이, 아이템이 아래에 위치한 경우 레이아웃 위치가 매우 아래에 위치하게 되는 문제 해결하기

**Comment by seokju2ng** [comment]
커스텀 아이템 height을 최근/북마크와 동일하게 수정
