### ISSUE TITLE
자동완성시 위/아래 이동이 안되는 버그

### ISSUE THREAD

**Issue by seokju2ng** [boostcamp-2020/Project15-B-Client-Based-Formula-Editor#99]
### 👉 Problem 
- `\`입력 후 자동완성이 안떠있을 때 위/아래로 움직이다가 다시 자동완성이 뜨게하면 위/아래로 선택할 수 없는 버그
![image](https://user-images.githubusercontent.com/43347250/102079883-d4987880-3e50-11eb-8426-39aaee0c44ff.png)

### 🏀 Solution
- 자동완성이 안떠있을 때 위/아래로 움직여도 문제가 없게 한다

### 👊 So We
- 자동완성 안떠있을 때 위/아래는 아무 동작도 하지 않게 한다.

**Comment by Woomin-Jeon** [comment]
이거 병재님이 처음 \에도 자동완성 뜨게 하시면서 이제 사라진 버그같아요

**Comment by enhakkore** [comment]
`'\'`만 입력해도 자동완성 레이아웃이 나타나게 수정하여 더이상 버그가 발생하지 않기때문에 이슈를 닫겠습니다😄
